### ISSUE TITLE
Schematic notes

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#21]
corrections for **exterm** schematics:
seen in git commit: 1d4d084

- [x] SND_SELECT should be ~{SND_SELECT} on page 7/8
- [x] pins I6 and I7 of C3 (PAL16L8) probably connect to other devices (not only to the pull-up resistor)
- [x] pin A14 of C9 (27C512) cannot be floating. 
- [x] Check if pins A14 and A15 if C9 and C11 are the same
- [x] Rename MAIN_AD to BANK1
- [x] Rename ~{RESET} to ~{SND_RST}
- [x] Rename CFG4 to ~{SND_RST'} and disconnect from CFG bus
- [x] There is no CFG5, reduce CFG bus to 3 bits
- [x] Rename CFG bus to BANK_CFG
- [x] Move down C3 so all wires enter straight (_el cable a I1 entra haciendo un quiebro_)

![imagen](https://user-images.githubusercontent.com/1863036/204352317-33fa885c-adc7-4c99-833d-7d5b997e4ee1.png)

**Comment by skutis** [comment]
It might be that they did not need the inputs to the PAL and reduced the equations from 
o13 = i8 & i9 & /i11 & /o15 + i3 & i8 & i9 & /i11 = i9 & /i11 & /o15 + i3 & i9 & /i11 
o14 = i5 & i7 & o15 + i6 & i7 & o15 = i5 & o15 + i6 & o15

I will check the PCB later.

**Comment by etriana85** [comment]
updated extermination schematic.
[exterm.pdf](https://github.com/jotego/jtbubl/files/10123794/exterm.pdf)
