### ISSUE TITLE
[insectx] schematic signals

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#22]
- [x] Rename SBSWD[1:0] to  SBANK[1:0], these two bits configure the active ROM bank (page)
- [x] Rename SBSWD2 to SET_LOCK1
- [x] Rename SBSWD3 to SET_LOCK2
- [x] Rename SBSWD4 to CNT_UP1
- [x] Rename SBSWD4 to CNT_UP2
- [x] Move the DIP switches to the same page as the YM2203
- [x] Delete the wire mess and leave the connection by labels between U51 and U43
![imagen](https://user-images.githubusercontent.com/1863036/204725317-7ac02350-7f4d-4d09-8dfc-b34f22491ef3.png)
- [ ] Align the transistor with the wire, so there are no corners
![imagen](https://user-images.githubusercontent.com/1863036/204732590-db72428a-6036-4378-a4fa-a7dc2bffcdc2.png)
- [x] Invert the order of the E bus in X1-004 to match the CPU signals
E3 becomes E0
E2 becomes E1
E1 becomes E2
![imagen](https://user-images.githubusercontent.com/1863036/204733635-557ec4fe-0da4-484e-911a-dcaf90533496.png)

**Comment by skutis** [comment]
I can fix it if you assign me.

**Comment by jotego** [comment]
Thank you. Please pull the repository first as we have just fixed the library file (it should be a link to the file in JTKICAD but it was just a plane file somehow)

**Comment by jotego** [comment]
The color signal indexes are messed up. The large resistors should connect to the small indexes. For instance, the 6kOhm resistor should connect to R0, because a change in R0 has little effect in the output due to the large impedance. 

The 1kOhm resistors are out of the binary sequence. They probably set a general brightness or tone for the image. I haven't seen references to that in the MAME docs so far. I suggest we do not count them in the color bus but give them a different name, like Rb, Bb, Gb where the b stands for brightness. That would be pins 1, 7 and 14.

![imagen](https://user-images.githubusercontent.com/1863036/205067685-57a057fe-59e9-42e9-bfde-1a2d8bc0e23c.png)

**Comment by skutis** [comment]
I will have a look at it tonight. When I think of it, the 1k did not make sense to me when I extracted the scehmatics from the PCB.

**Comment by jotego** [comment]
This is how @etriana85 did it for Insector X. I'm not sure what the DC in R/G/B DC stands for, it may just be a left over from a tentative name.

![imagen](https://user-images.githubusercontent.com/1863036/205075736-77dd7de7-7aef-477d-8c7c-0b5926c9b5a3.png)

**Comment by jotego** [comment]
I have checked all changes. Thank you
