### ISSUE TITLE
Insector X schematics, wrong connections in U36

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#28]
I think the MA15..9 connections in the PAL U36 are reversed. Pin 1 should be MA15 and then go on up to pin 7 = MA9.

As they are the /PALEN equation is trying to match addresses where A[13:9] is all ones, which makes no sense. Inverting the order the mapping will be A[15:11] all ones, which is the expected A ~ F800 to FFFF seen in MAME.

Another possibility is that they made a mistake in the PAL dump and the bits are sorted wrong there.

![imagen](https://user-images.githubusercontent.com/1863036/205859426-69df674b-284d-4d91-930c-a79fe7264251.png)

**Comment by skutis** [comment]
It seems they are reversed. It will be fixed as soon as I get to it.

**Comment by jotego** [comment]
Fixed in https://github.com/jotego/jtbubl/pull/30/commits/1c912c31f0f173f7e875a1bd47da29c5370299e6
