### ISSUE TITLE
Insector X schematics, wrong connections in U26

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#29]
The equation for /SWAIT is `o13 = i8 & i9 & /i11 & ( /o15 + i3 )` but according to the schematics `i9 = SBANK1`. SBANK1 is used as the A14 for the ROM when SA15 is high. This means that if the sound CPU tries to access that part of the ROM bank it will lock itself out. There is something wrong here.

![imagen](https://user-images.githubusercontent.com/1863036/205868107-652ebdca-5433-4a9e-954f-a0cd4569e90c.png)

**Comment by skutis** [comment]
I will check it when I get to it.

**Comment by jotego** [comment]
Fixed in https://github.com/jotego/jtbubl/pull/30/commits/1c912c31f0f173f7e875a1bd47da29c5370299e6
