### ISSUE TITLE
Common Ram Error

### ISSUE THREAD

**Issue by SinisterSpatula** [jotego/jtbubl#3]
Hi JT, for some reason I got a problem with "Common Ram Error" message displayed in the screen center and frozen game, within just a couple minutes of play (second stage).  I'm using 128mb module, and my memory passes at 140mhz in mem test.  I'll keep playing and see if it still happens more times.

Also noticed a missing upper right tile of the character in his bubble during the stage start.

**Comment by jotego** [comment]
Hello, not all MRA files work at the moment. There are hardware variations for bootlegs that are not implemented and some MRA files correspond to prototype versions of the game. That’s for Bubble Bobble.
For Tokio, which runs on the same RBF file, only the bootleg MRA works right now. 
Please try a different MRA file and let me know how it goes.
