### ISSUE TITLE
extermination schematics edits

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#33]
**GFX sheet resizing to A3**
- [x] Create new gfx_ram sheet with units B14, C14 (from main) and E13,E14,E16,E17 (from gfx)
- [x] Rename DBB bus to VD (_Video RAM data_, same name as in Insector X)
- [x] Rename GFX_A bus to VA (_Video RAM address_, same name as in Insector X)
- [x] Create new gfx_rom sheet with units A2,A4,A5,A7,A8,A10,A12,A13
- [x] Rename GFX_OE to ROM_OE
- [x] Rename GFX_CE to ROM_CE

**Color Mixer**
- [x] Rename F13 to F15 (MAME uses F15 in the ROM names)
- [x] Address bus **wrong** in symbol MB7124E. It should go from A0 to A8.

**MCU**
- [x] Move G15E, R20 from main to mcu
- [x] Rename port XTAL1 in main and mcu to H1B 

**SETA-X1-004**
- [x] Rename INC0 to SERVICE
- [x] Rename INC1 to TILT

**Other**
- [x] P26_DRQ is an output

**Comment by etriana85** [comment]
I have solved the issues additional.
