### ISSUE TITLE
Extermination schematics: change signal names for PAL output

### ISSUE THREAD

**Issue by jotego** [jotego/jtbubl#46]
Skutis brought our attention to a couple of signals called MAIN_Axx coming out of a PAL. That is misleading as they are not related to the main CPU address used in the name. One of them is the watchdog clear and the other is related to the video memory.

@etriana85 update the schematics with good signal names, please.

**Comment by etriana85** [comment]
Issue #46 Resolved. The names of the indicated signals have been corrected, as well as others.
I attach images, they are marked.

**Comment by etriana85** [comment]
![1](https://user-images.githubusercontent.com/92724765/214029713-d534373f-50c0-4f2a-b18f-d34a191273ef.png)
![2](https://user-images.githubusercontent.com/92724765/214029742-d5f2d409-d8f5-4b94-bf12-5010c3680fbb.png)
![3](https://user-images.githubusercontent.com/92724765/214029755-b8e99438-538b-47da-835c-e2dbbf8c1d35.png)
![4](https://user-images.githubusercontent.com/92724765/214029764-cd896c38-e38f-40c5-8ec2-fce32e9a150a.png)
![5](https://user-images.githubusercontent.com/92724765/214029784-010446dd-c828-4fcd-b8f4-5596e4bb9356.png)
![6](https://user-images.githubusercontent.com/92724765/214029798-705b1897-94b1-4f5a-b70c-6f1ad1c45cff.png)

**Comment by etriana85** [comment]
I have updated the datasheet of the symbol 74ls367, it had a link not found message.
I have moved the snd clock to the snd sheet, and some other gates, close to where the signals are generated, for those gates.
